create table customer_organization (
    id varchar(64) primary key,
    name varchar(255) not null,
    segment varchar(64) not null,
    headquarters varchar(255) not null,
    region varchar(128) not null,
    latitude double precision not null,
    longitude double precision not null,
    sector varchar(128) not null,
    annual_revenue_usd bigint not null
);

create table compliance_case (
    id varchar(64) primary key,
    client_id varchar(64) not null,
    case_name varchar(255) not null,
    priority varchar(32) not null,
    stage varchar(64) not null,
    status varchar(32) not null,
    jurisdiction varchar(128) not null,
    region varchar(128) not null,
    risk_score integer not null,
    stp_eligible boolean not null,
    first_time_right boolean not null,
    onboarding_hours double precision not null,
    assigned_to varchar(128) not null,
    completeness integer not null,
    narrative clob not null,
    next_best_action clob not null,
    constraint fk_case_client foreign key (client_id) references customer_organization (id)
);

create table document_submission (
    id varchar(64) primary key,
    case_id varchar(64) not null,
    type varchar(128) not null,
    status varchar(32) not null,
    completeness integer not null,
    uploaded_at timestamp with time zone not null,
    extracted_fields clob not null,
    constraint fk_document_case foreign key (case_id) references compliance_case (id)
);

create table policy_check_result (
    id varchar(64) primary key,
    case_id varchar(64) not null,
    label varchar(255) not null,
    status varchar(32) not null,
    rationale clob not null,
    constraint fk_policy_case foreign key (case_id) references compliance_case (id)
);

create table ownership_party (
    id varchar(64) primary key,
    case_id varchar(64) not null,
    name varchar(255) not null,
    role varchar(128) not null,
    group_name varchar(64) not null,
    constraint fk_ownership_party_case foreign key (case_id) references compliance_case (id)
);

create table ownership_relationship (
    id varchar(64) primary key,
    case_id varchar(64) not null,
    source_id varchar(64) not null,
    target_id varchar(64) not null,
    weight_value integer not null,
    constraint fk_ownership_relationship_case foreign key (case_id) references compliance_case (id)
);

create table monitoring_alert (
    id varchar(64) primary key,
    case_id varchar(64) not null,
    client_id varchar(64) not null,
    title varchar(255) not null,
    severity varchar(32) not null,
    region varchar(128) not null,
    latitude double precision not null,
    longitude double precision not null,
    event_time timestamp with time zone not null,
    false_positive_risk integer not null,
    description clob not null,
    constraint fk_alert_case foreign key (case_id) references compliance_case (id),
    constraint fk_alert_client foreign key (client_id) references customer_organization (id)
);

create table decision_record (
    id varchar(64) primary key,
    case_id varchar(64) not null,
    title varchar(255) not null,
    actor varchar(128) not null,
    decision varchar(32) not null,
    confidence integer not null,
    override_reason clob,
    created_at timestamp with time zone not null,
    constraint fk_decision_case foreign key (case_id) references compliance_case (id)
);

create table decision_reasoning_step (
    id bigint generated by default as identity primary key,
    decision_id varchar(64) not null,
    step_order integer not null,
    content clob not null,
    constraint fk_reasoning_decision foreign key (decision_id) references decision_record (id)
);

create table decision_evidence (
    id varchar(64) primary key,
    decision_id varchar(64) not null,
    label varchar(255) not null,
    type varchar(64) not null,
    confidence integer not null,
    excerpt clob not null,
    constraint fk_evidence_decision foreign key (decision_id) references decision_record (id)
);

create table agent_execution (
    id varchar(64) primary key,
    name varchar(255) not null,
    role varchar(128) not null,
    status varchar(32) not null,
    latency_ms integer not null,
    tasks_processed integer not null,
    auto_share integer not null,
    manual_share integer not null,
    pulse_message clob not null
);

create table activity_item (
    id varchar(64) primary key,
    title varchar(255) not null,
    description clob not null,
    timestamp timestamp with time zone not null,
    severity varchar(32) not null,
    route_hint varchar(32) not null
);

create table outbox_event (
    id varchar(64) primary key,
    aggregate_type varchar(128) not null,
    aggregate_id varchar(64) not null,
    event_type varchar(128) not null,
    payload clob not null,
    occurred_at timestamp with time zone not null
);

create table inbox_message (
    id varchar(64) primary key,
    message_type varchar(128) not null,
    payload clob not null,
    received_at timestamp with time zone not null
);

create table idempotency_key (
    id varchar(64) primary key,
    scope varchar(128) not null,
    created_at timestamp with time zone not null
);
