import type { CheckKycRequest } from '@/types/platform';

export const checkKycPayload: CheckKycRequest = {
  brandName: 'Harbor Commercial',
  formTitle: 'Corporate Account Opening Application',
  companyInfo: {
    legalName: 'Atlas Meridian Holdings, Inc.',
    tradingName: 'Atlas Meridian',
    entityType: 'Corporation',
    registrationNumber: 'C4839201',
    taxId: '12-3456789',
    incorporationDate: '2017-05-18',
    incorporationState: 'Delaware',
    incorporationCountry: 'United States',
    industry: 'Technology services',
    website: 'https://atlasmeridian.com',
    annualRevenue: '25000000',
    employeeCount: '120',
  },
  primaryContact: {
    fullName: 'Morgan Chen',
    title: 'Chief Financial Officer',
    email: 'morgan.chen@atlasmeridian.com',
    phone: '4155550199',
    extension: '204',
  },
  addresses: {
    registeredLine1: '100 Market Street',
    registeredLine2: 'Suite 1200',
    city: 'San Francisco',
    state: 'California',
    postalCode: '94105',
    country: 'United States',
    operatingSameAsRegistered: true,
    operatingLine1: '',
    operatingLine2: '',
    operatingCity: '',
    operatingState: '',
    operatingPostalCode: '',
    operatingCountry: 'United States',
  },
  bankingProfile: {
    accountPurpose: 'Operating account for client receipts and treasury disbursements',
    requestedProducts: ['Operating account', 'ACH origination'],
    expectedOpeningDeposit: '250000',
    monthlyIncoming: '900000',
    monthlyOutgoing: '720000',
    onlineBankingUsers: '2',
    internationalActivity: false,
    jurisdictionsInScope: '',
    needsCommercialCards: false,
  },
  beneficialOwners: [
    {
      id: 'owner-1',
      fullName: 'Morgan Chen',
      title: 'Chief Financial Officer',
      ownershipPercentage: '35',
      email: 'morgan.chen@atlasmeridian.com',
      phone: '4155550199',
      isAuthorizedSigner: true,
    },
  ],
  documents: {
    certificateOfFormation: true,
    taxIdLetter: true,
    ownershipChart: true,
    boardResolution: true,
    signerIdentification: false,
    addressProof: false,
  },
  declarations: {
    certifyAuthority: true,
    certifyBeneficialOwners: true,
    confirmTaxCompliance: true,
    confirmTerms: true,
  },
  additionalNotes: '',
};
