import { describe, expect, it } from "vitest";
import { DatabaseSync } from "node:sqlite";
import {
  describeDatabaseTable,
  DatabaseInsertAgentError,
  listDatabaseTables,
  runDatabaseInsertAgent,
} from "./databaseInsertAgent.js";

function createDatabase() {
  const database = new DatabaseSync(":memory:");

  database.exec(`
    CREATE TABLE business_information (
      business_name TEXT NOT NULL,
      control_number TEXT PRIMARY KEY,
      business_type TEXT NOT NULL,
      principal_business_address TEXT NOT NULL,
      designated_agent_name TEXT NOT NULL,
      status TEXT NOT NULL
    );
  `);

  return database;
}

describe("databaseInsertAgent", () => {
  it("lists available application tables", () => {
    const database = createDatabase();

    expect(listDatabaseTables(database)).toEqual([
      {
        name: "business_information",
        normalizedName: "business_information",
        label: "Business Information",
      },
    ]);
  });

  it("describes a table with form-friendly column metadata", () => {
    const database = createDatabase();

    expect(describeDatabaseTable(database, "business-information")).toEqual({
      tableName: "business_information",
      normalizedTableName: "business_information",
      label: "Business Information",
      columns: [
        {
          name: "business_name",
          normalizedName: "business_name",
          label: "Business Name",
          type: "TEXT",
          inputType: "text",
          options: [],
          required: true,
          primaryKey: false,
          autoGenerated: false,
          defaultValue: null,
          allowNull: false,
        },
        {
          name: "control_number",
          normalizedName: "control_number",
          label: "Control Number",
          type: "TEXT",
          inputType: "text",
          options: [],
          required: true,
          primaryKey: true,
          autoGenerated: false,
          defaultValue: null,
          allowNull: true,
        },
        {
          name: "business_type",
          normalizedName: "business_type",
          label: "Business Type",
          type: "TEXT",
          inputType: "text",
          options: [],
          required: true,
          primaryKey: false,
          autoGenerated: false,
          defaultValue: null,
          allowNull: false,
        },
        {
          name: "principal_business_address",
          normalizedName: "principal_business_address",
          label: "Principal Business Address",
          type: "TEXT",
          inputType: "textarea",
          options: [],
          required: true,
          primaryKey: false,
          autoGenerated: false,
          defaultValue: null,
          allowNull: false,
        },
        {
          name: "designated_agent_name",
          normalizedName: "designated_agent_name",
          label: "Designated Agent Name",
          type: "TEXT",
          inputType: "text",
          options: [],
          required: true,
          primaryKey: false,
          autoGenerated: false,
          defaultValue: null,
          allowNull: false,
        },
        {
          name: "status",
          normalizedName: "status",
          label: "Status",
          type: "TEXT",
          inputType: "select",
          options: ["Active", "Suspended", "Dissolved", "Noncompliance"],
          required: true,
          primaryKey: false,
          autoGenerated: false,
          defaultValue: null,
          allowNull: false,
        },
      ],
    });
  });

  it("inserts a row using normalized table and field names", () => {
    const database = createDatabase();

    const result = runDatabaseInsertAgent(database, {
      tableName: "business-information",
      data: {
        "business-name": "Northwind Treasury LLC",
        "control-number": "CN-1001",
        "business-type": "LLC",
        "principal-business-address": "100 Market Street, New York, NY 10001",
        "designated-agent-name": "Alex Morgan",
        status: "Active",
      },
    });

    const row = database
      .prepare("SELECT * FROM business_information WHERE control_number = ?")
      .get("CN-1001");

    expect(result).toEqual({
      agent: "database_insert",
      tableName: "business_information",
      insertedColumns: [
        "business_name",
        "control_number",
        "business_type",
        "principal_business_address",
        "designated_agent_name",
        "status",
      ],
      inserted: true,
    });
    expect(row).toEqual({
      business_name: "Northwind Treasury LLC",
      control_number: "CN-1001",
      business_type: "LLC",
      principal_business_address: "100 Market Street, New York, NY 10001",
      designated_agent_name: "Alex Morgan",
      status: "Active",
    });
  });

  it("rejects inserts into unknown tables", () => {
    const database = createDatabase();

    expect(() =>
      runDatabaseInsertAgent(database, {
        tableName: "missing-table",
        data: { id: "1" },
      }),
    ).toThrow(DatabaseInsertAgentError);
  });

  it("rejects rows with unknown columns", () => {
    const database = createDatabase();

    expect(() =>
      runDatabaseInsertAgent(database, {
        tableName: "business_information",
        data: {
          business_name: "Northwind Treasury LLC",
          control_number: "CN-1002",
          business_type: "LLC",
          principal_business_address: "100 Market Street, New York, NY 10001",
          designated_agent_name: "Alex Morgan",
          status: "Active",
          unsupported_field: "nope",
        },
      }),
    ).toThrow(DatabaseInsertAgentError);
  });

  it("rejects rows with invalid select options", () => {
    const database = createDatabase();

    expect(() =>
      runDatabaseInsertAgent(database, {
        tableName: "business_information",
        data: {
          business_name: "Northwind Treasury LLC",
          control_number: "CN-1004",
          business_type: "LLC",
          principal_business_address: "100 Market Street, New York, NY 10001",
          designated_agent_name: "Alex Morgan",
          status: "Archived",
        },
      }),
    ).toThrow(DatabaseInsertAgentError);
  });

  it("rejects rows that omit required columns", () => {
    const database = createDatabase();

    expect(() =>
      runDatabaseInsertAgent(database, {
        tableName: "business_information",
        data: {
          business_name: "Northwind Treasury LLC",
          control_number: "CN-1003",
        },
      }),
    ).toThrow(DatabaseInsertAgentError);
  });
});
