function normalizeIdentifier(value) {
  return String(value ?? "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function isSafeIdentifier(value) {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(value);
}

function buildLabel(identifier) {
  return String(identifier ?? "")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

function getTables(database) {
  return database
    .prepare(`
      SELECT name
      FROM sqlite_master
      WHERE type = 'table'
        AND name NOT LIKE 'sqlite_%'
      ORDER BY name ASC
    `)
    .all();
}

function findTable(database, tableName) {
  const normalizedTableName = normalizeIdentifier(tableName);

  if (!normalizedTableName) {
    throw new DatabaseInsertAgentError("A table name is required.", [
      { fieldKey: "tableName", message: "Provide a target table name." },
    ]);
  }

  const table = getTables(database).find(
    (candidate) => normalizeIdentifier(candidate.name) === normalizedTableName,
  );

  if (!table || !isSafeIdentifier(table.name)) {
    throw new DatabaseInsertAgentError("The requested table does not exist.", [
      { fieldKey: "tableName", message: `Unknown table: ${tableName}.` },
    ]);
  }

  return table.name;
}

function getTableColumns(database, tableName) {
  return database.prepare(`PRAGMA table_info(${tableName})`).all();
}

function getColumnOptions(tableName, columnName) {
  if (
    normalizeIdentifier(tableName) === "business_information" &&
    normalizeIdentifier(columnName) === "status"
  ) {
    return ["Active", "Suspended", "Dissolved", "Noncompliance"];
  }

  return [];
}

function inferInputType(column) {
  const type = String(column.type ?? "").trim().toUpperCase();
  const name = String(column.name ?? "").trim().toLowerCase();

  if (type.includes("INT") || type.includes("REAL") || type.includes("NUM")) {
    return "number";
  }

  if (name.includes("date") && name.includes("time")) {
    return "datetime-local";
  }

  if (name.endsWith("_at") || name.includes("timestamp")) {
    return "datetime-local";
  }

  if (name.includes("date")) {
    return "date";
  }

  if (type.includes("BOOL")) {
    return "checkbox";
  }

  if (
    name.includes("address") ||
    name.includes("payload") ||
    name.includes("notes") ||
    name.includes("result")
  ) {
    return "textarea";
  }

  return "text";
}

function normalizeRow(row) {
  if (!row || typeof row !== "object" || Array.isArray(row)) {
    throw new DatabaseInsertAgentError("A row object is required.", [
      { fieldKey: "data", message: "Provide row data as a JSON object." },
    ]);
  }

  const normalizedEntries = [];
  const seenKeys = new Set();

  Object.entries(row).forEach(([key, value]) => {
    const normalizedKey = normalizeIdentifier(key);

    if (!normalizedKey) {
      throw new DatabaseInsertAgentError("A row field name is invalid.", [
        { fieldKey: `data.${key}`, message: `Field name "${key}" is not valid.` },
      ]);
    }

    if (seenKeys.has(normalizedKey)) {
      throw new DatabaseInsertAgentError(
        "Duplicate row fields were provided after normalization.",
        [
          {
            fieldKey: `data.${key}`,
            message: `Field "${key}" conflicts with another provided field.`,
          },
        ],
      );
    }

    seenKeys.add(normalizedKey);
    normalizedEntries.push({ originalKey: key, normalizedKey, value });
  });

  if (!normalizedEntries.length) {
    throw new DatabaseInsertAgentError("At least one row field is required.", [
      { fieldKey: "data", message: "Provide at least one field to insert." },
    ]);
  }

  return normalizedEntries;
}

function isRequiredColumn(column) {
  const type = String(column.type ?? "").trim().toUpperCase();

  if (column.pk > 0) {
    return type !== "INTEGER";
  }

  return column.notnull === 1 && column.dflt_value === null;
}

function isAutoGeneratedColumn(column) {
  const type = String(column.type ?? "").trim().toUpperCase();
  return column.pk > 0 && type === "INTEGER";
}

export class DatabaseInsertAgentError extends Error {
  constructor(message, issues = []) {
    super(message);
    this.name = "DatabaseInsertAgentError";
    this.issues = issues;
  }
}

export function listDatabaseTables(database) {
  return getTables(database).map((table) => ({
    name: table.name,
    normalizedName: normalizeIdentifier(table.name),
    label: buildLabel(table.name),
  }));
}

export function describeDatabaseTable(database, tableName) {
  const resolvedTableName = findTable(database, tableName);
  const columns = getTableColumns(database, resolvedTableName);

  return {
    tableName: resolvedTableName,
    normalizedTableName: normalizeIdentifier(resolvedTableName),
    label: buildLabel(resolvedTableName),
    columns: columns.map((column) => {
      const options = getColumnOptions(resolvedTableName, column.name);

      return {
        name: column.name,
        normalizedName: normalizeIdentifier(column.name),
        label: buildLabel(column.name),
        type: String(column.type ?? "").trim() || "TEXT",
        inputType: options.length ? "select" : inferInputType(column),
        options,
        required: isRequiredColumn(column),
        primaryKey: column.pk > 0,
        autoGenerated: isAutoGeneratedColumn(column),
        defaultValue: column.dflt_value,
        allowNull: column.notnull !== 1,
      };
    }),
  };
}

export function runDatabaseInsertAgent(database, payload = {}) {
  const schema = describeDatabaseTable(database, payload.tableName);
  const tableName = schema.tableName;
  const columns = schema.columns;
  const columnByNormalizedName = new Map(
    columns.map((column) => [normalizeIdentifier(column.name), column]),
  );
  const normalizedEntries = normalizeRow(payload.data);
  const issues = [];

  normalizedEntries.forEach((entry) => {
    const matchedColumn = columnByNormalizedName.get(entry.normalizedKey);

    if (!matchedColumn) {
      issues.push({
        fieldKey: `data.${entry.originalKey}`,
        message: `Column "${entry.originalKey}" does not exist on ${tableName}.`,
      });
      return;
    }

    if (
      Array.isArray(matchedColumn.options) &&
      matchedColumn.options.length > 0 &&
      !matchedColumn.options.includes(entry.value)
    ) {
      issues.push({
        fieldKey: `data.${entry.originalKey}`,
        message: `Column "${matchedColumn.name}" must be one of: ${matchedColumn.options.join(", ")}.`,
      });
    }
  });

  const providedColumnNames = new Set(normalizedEntries.map((entry) => entry.normalizedKey));

  columns.forEach((column) => {
    if (column.required) {
      const normalizedColumnName = normalizeIdentifier(column.name);

      if (!providedColumnNames.has(normalizedColumnName)) {
        issues.push({
          fieldKey: `data.${column.name}`,
          message: `Column "${column.name}" is required for ${tableName}.`,
        });
      }
    }
  });

  if (issues.length) {
    throw new DatabaseInsertAgentError("The row is missing valid required fields.", issues);
  }

  const matchedColumns = normalizedEntries.map((entry) => columnByNormalizedName.get(entry.normalizedKey));
  const columnList = matchedColumns.map((column) => column.name).join(", ");
  const placeholders = matchedColumns.map(() => "?").join(", ");
  const values = normalizedEntries.map((entry) => entry.value);

  database
    .prepare(`INSERT INTO ${tableName} (${columnList}) VALUES (${placeholders})`)
    .run(...values);

  return {
    agent: "database_insert",
    tableName,
    insertedColumns: matchedColumns.map((column) => column.name),
    inserted: true,
  };
}
