export const defaultWorkspace = {
  brandName: "Harbor Commercial",
  formTitle: "Corporate Account Opening Application",
  intro:
    "Complete the information below to request a corporate operating account, treasury services, and digital banking access for your business.",
  activeStep: "company",
  lastUpdatedAt: null,
  supportEmail: "onboarding@harborcommercial.com",
  steps: [
    {
      id: "company",
      label: "Company",
      eyebrow: "01",
      title: "Corporate profile",
      detail: "Legal registration, tax details, and business classification.",
    },
    {
      id: "contact",
      label: "Contact",
      eyebrow: "02",
      title: "Primary contact and address",
      detail: "Who we should work with and where the business is registered.",
    },
    {
      id: "banking",
      label: "Banking",
      eyebrow: "03",
      title: "Account requirements",
      detail: "Products requested, deposit expectations, and transaction profile.",
    },
    {
      id: "ownership",
      label: "Ownership",
      eyebrow: "04",
      title: "Beneficial owners and signers",
      detail: "Individuals with ownership and authority over the account.",
    },
    {
      id: "documents",
      label: "Review",
      eyebrow: "05",
      title: "Documents and declarations",
      detail: "Application checklist, certifications, and final confirmations.",
    },
  ],
  entityTypeOptions: [
    "Corporation",
    "Limited Liability Company",
    "Limited Partnership",
    "General Partnership",
    "Nonprofit Corporation",
    "Professional Corporation",
  ],
  industryOptions: [
    "Technology services",
    "Distribution and wholesale",
    "Manufacturing",
    "Healthcare services",
    "Professional services",
    "Construction and engineering",
    "Real estate management",
    "Transportation and logistics",
  ],
  countryOptions: [
    "United States",
    "Canada",
    "United Kingdom",
    "Germany",
    "Singapore",
    "Mexico",
  ],
  stateOptions: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "District of Columbia",
  ],
  productOptions: [
    "Operating account",
    "Interest-bearing business savings",
    "ACH origination",
    "Domestic wires",
    "International wires",
    "Commercial debit cards",
    "Treasury management portal",
  ],
  documentOptions: [
    {
      key: "certificateOfFormation",
      title: "Certificate of formation / incorporation",
      detail: "Filed formation document issued by the registering authority.",
    },
    {
      key: "taxIdLetter",
      title: "IRS EIN / tax identification letter",
      detail: "Official confirmation of the entity's tax registration.",
    },
    {
      key: "ownershipChart",
      title: "Ownership chart",
      detail: "Current ownership structure through ultimate beneficial owners.",
    },
    {
      key: "boardResolution",
      title: "Board resolution or banking authority letter",
      detail: "Approval authorizing account opening and designated signers.",
    },
    {
      key: "signerIdentification",
      title: "Government ID for each signer",
      detail: "Valid identity document for every authorized signer.",
    },
    {
      key: "addressProof",
      title: "Proof of registered business address",
      detail: "Utility bill, lease, or official filing showing the address.",
    },
  ],
  declarationOptions: [
    {
      key: "certifyAuthority",
      title: "I confirm I am authorized to submit this application on behalf of the business.",
      detail: "Required",
      required: true,
    },
    {
      key: "certifyBeneficialOwners",
      title: "I certify the beneficial ownership information provided is complete and accurate.",
      detail: "Required",
      required: true,
    },
    {
      key: "confirmTaxCompliance",
      title: "I confirm the business will provide any required tax forms and compliance documentation.",
      detail: "Required",
      required: true,
    },
    {
      key: "confirmTerms",
      title: "I understand account opening is subject to bank review, verification, and approval.",
      detail: "Required",
      required: true,
    },
  ],
  companyInfo: {
    legalName: "",
    tradingName: "",
    entityType: "Corporation",
    registrationNumber: "",
    taxId: "",
    incorporationDate: "",
    incorporationState: "",
    incorporationCountry: "United States",
    industry: "",
    website: "",
    annualRevenue: "",
    employeeCount: "",
  },
  primaryContact: {
    fullName: "",
    title: "",
    email: "",
    phone: "",
    extension: "",
  },
  addresses: {
    registeredLine1: "",
    registeredLine2: "",
    city: "",
    state: "",
    postalCode: "",
    country: "United States",
    operatingSameAsRegistered: true,
    operatingLine1: "",
    operatingLine2: "",
    operatingCity: "",
    operatingState: "",
    operatingPostalCode: "",
    operatingCountry: "United States",
  },
  bankingProfile: {
    accountPurpose: "",
    requestedProducts: ["Operating account"],
    expectedOpeningDeposit: "250000",
    monthlyIncoming: "",
    monthlyOutgoing: "",
    onlineBankingUsers: "2",
    internationalActivity: false,
    jurisdictionsInScope: "",
    needsCommercialCards: false,
  },
  beneficialOwners: [
    {
      id: "owner-1",
      fullName: "",
      title: "",
      ownershipPercentage: "",
      email: "",
      phone: "",
      isAuthorizedSigner: true,
    },
  ],
  documents: {
    certificateOfFormation: false,
    taxIdLetter: false,
    ownershipChart: false,
    boardResolution: false,
    signerIdentification: false,
    addressProof: false,
  },
  declarations: {
    certifyAuthority: false,
    certifyBeneficialOwners: false,
    confirmTaxCompliance: false,
    confirmTerms: false,
  },
  additionalNotes: "",
  submission: {
    status: "draft",
    referenceId: null,
    submittedAt: null,
    overallDecision: "not_started",
    summary:
      "When you submit the application, the orchestrator will run KYC, AML, document processing, and risk review.",
    recommendedAction: "Complete the application and submit it for automated review.",
  },
  orchestration: {
    status: "idle",
    startedAt: null,
    completedAt: null,
    summary:
      "No automated review has run yet. Submission starts the onboarding orchestrator.",
    checks: {
      kyc: {
        key: "kyc",
        label: "KYC",
        status: "not_started",
        decision: "pending",
        summary: "Pending submission.",
        flags: [],
        integration: {
          checkKyc: null,
        },
      },
      aml: {
        key: "aml",
        label: "AML",
        status: "not_started",
        decision: "pending",
        summary: "Pending submission.",
        flags: [],
      },
      documentProcessing: {
        key: "documentProcessing",
        label: "Document processing",
        status: "not_started",
        decision: "pending",
        summary: "Pending submission.",
        flags: [],
      },
      risk: {
        key: "risk",
        label: "Risk",
        status: "not_started",
        decision: "pending",
        summary: "Pending submission.",
        flags: [],
        score: null,
        integration: {
          checkRisk: null,
        },
      },
    },
    integrations: {
      checkKyc: null,
      checkRisk: null,
    },
  },
};
