import { startTransition, useEffect, useId, useState } from "react";
import {
  describeDatabaseTable,
  insertDatabaseRow,
  listDatabaseTables,
} from "./api";

function isBlankValue(value) {
  if (typeof value === "boolean") {
    return false;
  }

  return String(value ?? "").trim().length === 0;
}

function normalizeValueForInsert(column, value) {
  if (column.inputType === "checkbox") {
    return value ? 1 : 0;
  }

  if (column.inputType === "number") {
    if (isBlankValue(value)) {
      return null;
    }

    const numericValue = Number(value);
    return Number.isFinite(numericValue) ? numericValue : value;
  }

  const normalizedValue = String(value ?? "").trim();
  return normalizedValue ? normalizedValue : null;
}

function isValidValue(column, value) {
  if (!column.required && isBlankValue(value)) {
    return true;
  }

  if (column.inputType === "checkbox") {
    return typeof value === "boolean";
  }

  if (column.inputType === "select") {
    return !isBlankValue(value) && (column.options ?? []).includes(value);
  }

  if (column.inputType === "number") {
    return !isBlankValue(value) && Number.isFinite(Number(value));
  }

  return !isBlankValue(value);
}

function formatValuePreview(column, value) {
  if (value === null || value === undefined || value === "") {
    return "Skipped";
  }

  if (column.inputType === "checkbox") {
    return value ? "Yes" : "No";
  }

  return String(value);
}

function buildPrompt(column) {
  const requirement = column.required ? "This field is required." : "This field is optional.";
  return `Please enter ${column.label.toLowerCase()}. ${requirement}`;
}

function getInitialValue(column) {
  return column?.inputType === "checkbox" ? false : "";
}

function getInsertableColumns(schema) {
  return (schema?.columns ?? []).filter((column) => !column.autoGenerated);
}

function getFriendlyErrorMessage(error, fallbackMessage) {
  const issueMessage = error?.payload?.issues?.[0]?.message;

  if (issueMessage) {
    return issueMessage;
  }

  if (error?.name === "UnexpectedApiPayloadError") {
    return "The running API server returned the wrong response for table metadata. Restart `npm run dev:api` so it picks up the latest routes.";
  }

  if (error?.status === 404 || /route not found/i.test(String(error?.message ?? ""))) {
    return "The running API server does not have the database assistant routes yet. Restart `npm run dev:api` and refresh the page.";
  }

  if (error?.name === "TypeError" || /failed to fetch/i.test(String(error?.message ?? ""))) {
    return "The database assistant could not reach the API server. Start `npm run dev:api` and try again.";
  }

  return error?.message ?? fallbackMessage;
}

export function TableInsertAssistant({ onClose }) {
  const dialogTitleId = useId();
  const dialogDescriptionId = useId();
  const [availableTables, setAvailableTables] = useState([]);
  const [availableTablesState, setAvailableTablesState] = useState("loading");
  const [tableNameInput, setTableNameInput] = useState("");
  const [tableLookupState, setTableLookupState] = useState("idle");
  const [schema, setSchema] = useState(null);
  const [fieldValues, setFieldValues] = useState({});
  const [currentFieldIndex, setCurrentFieldIndex] = useState(0);
  const [currentInputValue, setCurrentInputValue] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [saveState, setSaveState] = useState("idle");
  const [successMessage, setSuccessMessage] = useState("");

  const insertableColumns = getInsertableColumns(schema);
  const currentColumn = insertableColumns[currentFieldIndex] ?? null;
  const completedColumns =
    saveState === "saved"
      ? insertableColumns
      : insertableColumns.slice(0, currentFieldIndex);
  const canSaveCurrentField = currentColumn
    ? isValidValue(currentColumn, currentInputValue)
    : false;

  useEffect(() => {
    let ignore = false;

    async function loadTables() {
      try {
        const response = await listDatabaseTables();
        const nextTables = response.tables ?? [];

        if (ignore) {
          return;
        }

        startTransition(() => {
          setAvailableTables(nextTables);
          setTableNameInput((currentValue) => currentValue || nextTables[0]?.name || "");
          setAvailableTablesState("loaded");
        });
      } catch (error) {
        if (ignore) {
          return;
        }

        setAvailableTables([]);
        setAvailableTablesState("error");
        setErrorMessage(
          getFriendlyErrorMessage(error, "Unable to load the table list right now."),
        );
      }
    }

    loadTables();

    return () => {
      ignore = true;
    };
  }, []);

  useEffect(() => {
    function handleKeyDown(event) {
      if (event.key === "Escape") {
        onClose();
      }
    }

    document.body.style.overflow = "hidden";
    window.addEventListener("keydown", handleKeyDown);

    return () => {
      document.body.style.overflow = "";
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [onClose]);

  useEffect(() => {
    setCurrentInputValue(fieldValues[currentColumn?.name] ?? getInitialValue(currentColumn));
  }, [currentColumn, fieldValues]);

  async function handleTableSubmit(event) {
    event.preventDefault();
    setErrorMessage("");
    setSuccessMessage("");
    setTableLookupState("loading");

    try {
      const nextSchema = await describeDatabaseTable(tableNameInput);
      const nextColumns = getInsertableColumns(nextSchema);

      if (!nextColumns.length) {
        throw new Error("This table does not expose any editable fields.");
      }

      startTransition(() => {
        setSchema(nextSchema);
        setFieldValues({});
        setCurrentFieldIndex(0);
        setTableNameInput(nextSchema.tableName);
        setCurrentInputValue(getInitialValue(nextColumns[0]));
        setTableLookupState("loaded");
        setSaveState("idle");
      });
    } catch (error) {
      setTableLookupState("error");
      setErrorMessage(getFriendlyErrorMessage(error, "Unable to load that table right now."));
    }
  }

  async function handleAdvance(event) {
    event.preventDefault();

    if (!currentColumn) {
      return;
    }

    if (!isValidValue(currentColumn, currentInputValue)) {
      setErrorMessage(
        currentColumn.required
          ? `${currentColumn.label} is required before you continue.`
          : `Enter a valid value for ${currentColumn.label.toLowerCase()}.`,
      );
      return;
    }

    const nextFieldValues = {
      ...fieldValues,
      [currentColumn.name]: normalizeValueForInsert(currentColumn, currentInputValue),
    };

    setErrorMessage("");

    if (currentFieldIndex === insertableColumns.length - 1) {
      setSaveState("saving");

      try {
        await insertDatabaseRow(schema.tableName, nextFieldValues);
        startTransition(() => {
          setFieldValues(nextFieldValues);
          setSaveState("saved");
          setSuccessMessage(`Saved a new row to ${schema.tableName}.`);
        });
      } catch (error) {
        setSaveState("error");
        setErrorMessage(getFriendlyErrorMessage(error, "The row could not be saved."));
      }

      return;
    }

    startTransition(() => {
      setFieldValues(nextFieldValues);
      setCurrentFieldIndex((index) => index + 1);
    });
  }

  function handleStartAnotherRow() {
    if (!insertableColumns.length) {
      return;
    }

    startTransition(() => {
      setFieldValues({});
      setCurrentFieldIndex(0);
      setCurrentInputValue(getInitialValue(insertableColumns[0]));
      setErrorMessage("");
      setSuccessMessage("");
      setSaveState("idle");
    });
  }

  function handleChangeTable() {
    startTransition(() => {
      setSchema(null);
      setFieldValues({});
      setCurrentFieldIndex(0);
      setCurrentInputValue("");
      setErrorMessage("");
      setSuccessMessage("");
      setSaveState("idle");
      setTableLookupState("idle");
    });
  }

  return (
    <div
      className="table-agent-modal"
      role="presentation"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) {
          onClose();
        }
      }}
    >
      <section
        className="table-agent-window"
        role="dialog"
        aria-modal="true"
        aria-labelledby={dialogTitleId}
        aria-describedby={dialogDescriptionId}
      >
        <div className="table-agent-grid">
        <div className="table-agent-panel">
          <div className="table-agent-header">
            <div className="table-agent-header-row">
              <div>
            <p className="section-eyebrow">Table insert assistant</p>
                <h2 id={dialogTitleId}>Chat your way into any SQLite table</h2>
                <p id={dialogDescriptionId}>
                  Enter a table name and the assistant will inspect its structure,
                  ask for each field one by one, and save the row when you finish.
                </p>
              </div>
              <button
                type="button"
                className="table-agent-close"
                onClick={onClose}
                aria-label="Close database assistant"
              >
                Close
              </button>
            </div>
          </div>

          <div className="table-agent-chat" aria-live="polite">
            <article className="table-agent-message assistant">
              <p className="table-agent-role">Assistant</p>
              <p>Which table would you like to add data to?</p>
            </article>

            {schema ? (
              <>
                <article className="table-agent-message user">
                  <p className="table-agent-role">You</p>
                  <p>{schema.tableName}</p>
                </article>
                <article className="table-agent-message assistant">
                  <p className="table-agent-role">Assistant</p>
                  <p>
                    I found {insertableColumns.length} field
                    {insertableColumns.length === 1 ? "" : "s"} for{" "}
                    <strong>{schema.label}</strong>. I&apos;ll guide you through them one at a
                    time.
                  </p>
                </article>
                {completedColumns.map((column) => (
                  <div key={column.name} className="table-agent-transcript-pair">
                    <article className="table-agent-message assistant">
                      <p className="table-agent-role">Assistant</p>
                      <p>{buildPrompt(column)}</p>
                    </article>
                    <article className="table-agent-message user">
                      <p className="table-agent-role">You</p>
                      <p>{formatValuePreview(column, fieldValues[column.name])}</p>
                    </article>
                  </div>
                ))}
                {saveState === "saved" ? (
                  <article className="table-agent-message assistant success">
                    <p className="table-agent-role">Assistant</p>
                    <p>{successMessage}</p>
                  </article>
                ) : currentColumn ? (
                  <article className="table-agent-message assistant">
                    <p className="table-agent-role">Assistant</p>
                    <p>{buildPrompt(currentColumn)}</p>
                  </article>
                ) : null}
              </>
            ) : null}
          </div>

          {!schema ? (
            <form className="table-agent-composer" onSubmit={handleTableSubmit}>
              <label className={`field${errorMessage ? " has-error" : ""}`}>
                <span>Table name</span>
                <select
                  value={tableNameInput}
                  onChange={(event) => setTableNameInput(event.target.value)}
                  required
                  disabled={availableTablesState === "loading" || !availableTables.length}
                >
                  <option value="">
                    {availableTablesState === "loading"
                      ? "Loading tables..."
                      : availableTablesState === "error"
                        ? "Unable to load tables"
                        : availableTables.length
                        ? "Select a table"
                        : "No tables available"}
                  </option>
                  {availableTables.map((table) => (
                    <option key={table.name} value={table.name}>
                      {table.label}
                    </option>
                  ))}
                </select>
              </label>
              {errorMessage ? <p className="field-error-copy">{errorMessage}</p> : null}
              <div className="table-agent-actions">
                <button
                  type="submit"
                  className="primary-button"
                  disabled={!tableNameInput.trim() || tableLookupState === "loading"}
                >
                  {tableLookupState === "loading" ? "Loading table..." : "Next"}
                </button>
              </div>
            </form>
          ) : saveState === "saved" ? (
            <div className="table-agent-actions">
              <button
                type="button"
                className="primary-button"
                onClick={handleStartAnotherRow}
              >
                Add another row
              </button>
              <button
                type="button"
                className="secondary-button"
                onClick={handleChangeTable}
              >
                Change table
              </button>
            </div>
          ) : currentColumn ? (
            <form className="table-agent-composer" onSubmit={handleAdvance}>
              {currentColumn.inputType === "checkbox" ? (
                <label className="inline-toggle table-agent-toggle">
                  <input
                    type="checkbox"
                    checked={Boolean(currentInputValue)}
                    onChange={(event) => setCurrentInputValue(event.target.checked)}
                  />
                  <span>
                    Mark <strong>{currentColumn.label}</strong> as enabled.
                  </span>
                </label>
              ) : currentColumn.inputType === "select" ? (
                <label className={`field${errorMessage ? " has-error" : ""}`}>
                  <span>
                    {currentColumn.label}
                    <span className="table-agent-helper-inline">
                      Choose one option
                    </span>
                  </span>
                  <select
                    value={currentInputValue ?? ""}
                    onChange={(event) => setCurrentInputValue(event.target.value)}
                    required={currentColumn.required}
                  >
                    <option value="">
                      {currentColumn.required ? "Select a value" : "Skip this field"}
                    </option>
                    {(currentColumn.options ?? []).map((option) => (
                      <option key={option} value={option}>
                        {option}
                      </option>
                    ))}
                  </select>
                </label>
              ) : (
                <label className={`field${errorMessage ? " has-error" : ""}`}>
                  <span>
                    {currentColumn.label}
                    <span className="table-agent-helper-inline">
                      {currentColumn.required
                        ? "Required field"
                        : "Optional field. Leave blank if you want to skip it."}
                    </span>
                  </span>
                  {currentColumn.inputType === "textarea" ? (
                    <textarea
                      className="field-textarea"
                      value={currentInputValue ?? ""}
                      onChange={(event) => setCurrentInputValue(event.target.value)}
                      placeholder={currentColumn.label}
                      rows={4}
                      required={currentColumn.required}
                    />
                  ) : (
                    <input
                      type={currentColumn.inputType}
                      value={currentInputValue ?? ""}
                      onChange={(event) => setCurrentInputValue(event.target.value)}
                      placeholder={currentColumn.label}
                      required={currentColumn.required}
                    />
                  )}
                </label>
              )}

              {errorMessage ? <p className="field-error-copy">{errorMessage}</p> : null}

              <div className="table-agent-actions">
                <button
                  type="button"
                  className="secondary-button"
                  onClick={handleChangeTable}
                >
                  Change table
                </button>
                <button
                  type="submit"
                  className="primary-button"
                  disabled={!canSaveCurrentField || saveState === "saving"}
                >
                  {currentFieldIndex === insertableColumns.length - 1
                    ? saveState === "saving"
                      ? "Saving..."
                      : "Save"
                    : "Next field"}
                </button>
              </div>
            </form>
          ) : null}
        </div>

        <aside className="summary-panel summary-panel-light table-agent-sidebar">
          <div className="summary-card">
            <p className="section-eyebrow">Available tables</p>
            <h3>Database targets</h3>
            {availableTablesState === "loading" ? (
              <p className="progress-copy">Inspecting the database...</p>
            ) : availableTablesState === "error" ? (
              <p className="progress-copy">
                Table suggestions are temporarily unavailable, but you can still
                enter a name manually.
              </p>
            ) : (
              <div className="table-agent-table-list">
                {availableTables.map((table) => (
                  <button
                    key={table.name}
                    type="button"
                    className={`table-agent-table-chip${
                      schema?.tableName === table.name ? " active" : ""
                    }`}
                    onClick={() => setTableNameInput(table.name)}
                  >
                    {table.name}
                  </button>
                ))}
              </div>
            )}
          </div>

          <div className="summary-card">
            <p className="section-eyebrow">Field queue</p>
            <h3>{schema?.label ?? "No table selected"}</h3>
            {schema ? (
              <div className="table-agent-field-list">
                {insertableColumns.map((column, index) => (
                  <div
                    key={column.name}
                    className={`table-agent-field-item${
                      index < currentFieldIndex || saveState === "saved"
                        ? " complete"
                        : index === currentFieldIndex
                          ? " current"
                          : ""
                    }`}
                  >
                    <div>
                      <strong>{column.label}</strong>
                      <span>{column.type}</span>
                    </div>
                    <span>
                      {index < currentFieldIndex || saveState === "saved"
                        ? "Collected"
                        : index === currentFieldIndex
                          ? "Current"
                          : column.required
                            ? "Required"
                            : "Optional"}
                    </span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="progress-copy">
                Once you choose a table, the assistant will map its fields here.
              </p>
            )}
          </div>

          <div className="summary-card">
            <p className="section-eyebrow">Collected answers</p>
            <h3>Ready to save</h3>
            {Object.keys(fieldValues).length ? (
              <div className="summary-rows">
                {insertableColumns
                  .filter((column) => Object.prototype.hasOwnProperty.call(fieldValues, column.name))
                  .map((column) => (
                    <div key={column.name} className="summary-row">
                      <span>{column.label}</span>
                      <strong>{formatValuePreview(column, fieldValues[column.name])}</strong>
                    </div>
                  ))}
              </div>
            ) : (
              <p className="progress-copy">
                Answers will appear here as you move through the conversation.
              </p>
            )}
          </div>
        </aside>
        </div>
      </section>
    </div>
  );
}
